version: '3.7'
services:
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3307:3306"
    networks:
      - db_network
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: opendsa
      MYSQL_DATABASE: opendsa
      MYSQL_USER: opendsa
      MYSQL_PASSWORD: opendsa

  opendsa-lti:
    build:
      context: ./opendsa-lti
      dockerfile: Dockerfile
      args:
        - RAILS_ENV=development
        - ODSA_BRANCH=master
        - LTI_BRANCH=docker-compose
    image: opendsa/opendsa-lti:latest
    volumes:
      - ./opendsa-lti:/opendsa-lti
      - ./opendsa:/opendsa
      - staticvolume:/opendsa-lti/public/assets
      - bundle:/usr/local/bundle
      - cache:/cache # added to support windows
    entrypoint: /opendsa-lti/docker-entrypoint.sh
    command: ["./scripts/start.sh"]
    networks:
      - db_network
      - nginx_network
    expose:
      - 8443
    depends_on:
      - db
    environment:
      - SPROCKETS_CACHE=/cache # added to support windows

  codeworkout:
    build:
      context: ./code-workout
      dockerfile: Dockerfile
    image: code-workout:latest
    volumes:
      - ./code-workout:/code-workout
    stdin_open: true
    tty: true
    networks:
      - db_network
      - nginx_network
    expose:
      - 9292
    depends_on:
      - db

networks:
  db_network:
    driver: bridge
  nginx_network:
    driver: bridge
volumes:
  db:
  staticvolume:
  bundle:
  cache: # added to support windows
