version: '3.7'
services:
  setup:
    profiles: ['setup']
    build:
      context: .
      dockerfile: Dockerfile
    image: devstack:latest
    stdin_open: true
    tty: true
    volumes:
      - .:/devstack

  db:
    profiles: ['lti', 'code-workout', 'cw-op', 'odsa-cw']
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3307:3306"
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: opendsa
      MYSQL_DATABASE: opendsa
      MYSQL_USER: opendsa
      MYSQL_PASSWORD: opendsa

  opendsa:
    profiles: ['opendsa']
    build:
      context: ./opendsa
      dockerfile: Dockerfile
    image: opendsa/opendsa:latest
    command: ["./scripts/start.sh"]
    volumes:
      - ./opendsa:/opendsa
    expose:
      - 8080
    depends_on:
      - proxy
    labels:
      traefik.http.routers.opendsa.rule: Host(`opendsa.localhost.devcom.vt.edu`)
      traefik.http.services.opendsa.loadbalancer.server.port: 8080

  opendsa-server:
    profiles: ['lti', 'odsa-cw']
    build:
      context: ./opendsa
      dockerfile: Dockerfile.flask
    image: opendsa/opendsa-server:latest
    command: ["python", "api.py"]
    volumes:
      - ./opendsa:/opendsa
    expose:
      - 8082
    labels:
      traefik.http.routers.opendsa-server.rule: Host(`opendsa-server.localhost.devcom.vt.edu`)
      traefik.http.services.opendsa-server.loadbalancer.server.port: 8082

  opendsa-lti:
    profiles: ['lti', 'odsa-cw']
    build:
      context: ./opendsa-lti
      dockerfile: Dockerfile
      args:
        - RAILS_ENV=development
        - ODSA_BRANCH=docker-lti
        - LTI_BRANCH=docker-lti
    image: opendsa/opendsa-lti:latest
    volumes:
      - ./opendsa-lti:/opendsa-lti
      - ./opendsa:/opendsa
      - staticvolume:/opendsa-lti/public/assets
      - bundle:/usr/local/bundle
      - cache:/cache # added to support windows
    entrypoint: /opendsa-lti/docker-entrypoint.sh
    command: ["./scripts/start.sh"]
    expose:
      - 8443
    depends_on:
      - db
      - proxy
      - opendsa-server
    environment:
      - SPROCKETS_CACHE=/cache # added to support windows
    labels:
      traefik.http.routers.opendsa-lti.rule: Host(`opendsa-lti.localhost.devcom.vt.edu`)
      traefik.http.services.opendsa-lti.loadbalancer.server.port: 8443

  code-workout:
    profiles: ['code-workout', 'cw-op', 'odsa-cw']
    build:
      context: ./code-workout
      dockerfile: Dockerfile
    image: code-workout:latest
    volumes:
      - ./code-workout:/code-workout
      - cache:/cache # added to support windows
    stdin_open: true
    tty: true
    expose:
      - 9292
    depends_on:
      - db
      - proxy
    environment:
      - SPROCKETS_CACHE=/cache # added to support windows
    labels:
      traefik.http.routers.code-workout.rule: Host(`code-workout.localhost.devcom.vt.edu`)
      traefik.http.services.code-workout.loadbalancer.server.port: 9292

  openpop:
    profiles: ['openpop', 'cw-op']
    build:
      context: ./openpop
      dockerfile: Dockerfile
    image: openpop:latest
    command: ["./runservers.sh"]
    volumes:
      - ./openpop:/openpop
    expose:
      - 9295
    depends_on:
      - proxy
    labels:
      traefik.http.routers.openpop.rule: Host(`openpop.localhost.devcom.vt.edu`)
      traefik.http.services.openpop.loadbalancer.server.port: 9295

  proxy:
    profiles: ['opendsa', 'lti', 'code-workout', 'openpop', 'cw-op', 'odsa-cw']
    image: dtr.it.vt.edu/devcom/devcom-localhost-proxy:traefik-2.3
    ports:
      - 80:80
      - 443:443
      - 127.0.0.1:8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      default:
        aliases: # Ensure all container-to-container HTTP requests go through the proxy
          - opendsa.localhost.devcom.vt.edu
          - opendsa-lti.localhost.devcom.vt.edu
          - code-workout.localhost.devcom.vt.edu
          - openpop.localhost.devcom.vt.edu
          - opendsa-server.localhost.devcom.vt.edu

volumes:
  db:
  staticvolume:
  bundle:
  cache: # added to support windows
