version: '3.7'
services:
  nginx:
    build: ./nginx
    tty: true
    command: [nginx-debug, '-g', 'daemon off;']
    ports:
      - 80:80
      - 443:443
    networks:
      - nginx_network
    volumes:
      - staticvolume:/opendsa-lti/public/assets
    depends_on:
      - opendsa-lti