version: '3.7'
services:
  setup:
    profiles: ["setup"]
    build:
      context: .
      dockerfile: Dockerfile
    image: devstack:latest
    stdin_open: true
    tty: true
    volumes:
      - .:/devstack

  db:
    profiles: ["lti", "codeworkout"]
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3307:3306"
    networks:
      - db_network
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: opendsa
      MYSQL_DATABASE: opendsa
      MYSQL_USER: opendsa
      MYSQL_PASSWORD: opendsa

  opendsa-lti:
    profiles: ['lti']
    build:
      context: ./opendsa-lti
      dockerfile: Dockerfile
      args:
        - RAILS_ENV=development
        - ODSA_BRANCH=master
        - LTI_BRANCH=master
    image: opendsa/opendsa-lti:latest
    volumes:
      - ./opendsa-lti:/opendsa-lti
      - ./opendsa:/opendsa
      - staticvolume:/opendsa-lti/public/assets
      - bundle:/usr/local/bundle
      - cache:/cache # added to support windows
    entrypoint: /opendsa-lti/docker-entrypoint.sh
    command: ["./scripts/start.sh"]
    networks:
      - db_network
      - nginx_network
    expose:
      - 8443
    depends_on:
      - db
    environment:
      - SPROCKETS_CACHE=/cache # added to support windows

  codeworkout:
    profiles: ['codeworkout']
    build:
      context: ./code-workout
      dockerfile: Dockerfile
    image: code-workout:latest
    volumes:
      - ./code-workout:/code-workout
    stdin_open: true
    tty: true
    networks:
      - db_network
      - nginx_network
    expose:
      - 9292
    depends_on:
      - db

  # Alex question: what is nginx for?  What profile is best for it? 
  nginx:
    profiles: ["lti", 'codeworkout']
    build: ./nginx
    image: opendsa/nginx:latest
    tty: true
    command: [ nginx-debug, '-g', 'daemon off;' ]
    ports:
      - 8443:8443
      - 9292:9292
    networks:
      - nginx_network
    volumes:
      - staticvolume:/opendsa-lti/public/assets
    depends_on:
      - opendsa-lti
      - codeworkout

networks:
  db_network:
    driver: bridge
  nginx_network:
    driver: bridge
volumes:
  db:
  staticvolume:
  bundle:
  cache: # added to support windows
