version: '3.7'
services:
  nginx:
    build: ./nginx
    tty: true
    command: [nginx-debug, '-g', 'daemon off;']
    ports:
      - 8000:80
    networks:
      - nginx_network
    depends_on:
      - opendsa-lti